### ISSUE TITLE
design: storybook 및 기타 변동사항 수정

### ISSUE THREAD

**Issue by azure-553** [dnd-side-project/dnd-11th-10-frontend#104]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

<br />

- merge로 인해 생긴 변동사항을 수정합니다

## ✅ To-do
- [x] Chip Storybook 수정
- [x] JobGroupCard Storybook 수정
- [x] 잃어버린 loading page 추가
