### ISSUE TITLE
feat: 학습 홈 비회원 입장 시 BottomSheet 추가 및 능력치 표기 방식 수정

### ISSUE THREAD

**Issue by lsy20140** [dnd-side-project/dnd-11th-10-frontend#124]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

- 구글 소셜 로그인 시 유저 ID 전역 상태로 관리 -> 현재 사용자 로그인 여부 확인 및 식별
- 학습 홈에 비회원 입장 시 보여줄 BottomSheet variant 추가(다음에 할게요 선택 여부 localStorage에 저장)
- 비회원 학습 탭 능력치 상위 퍼센트 "??"로 표기 방식 변경

<br />

## ✅ To-do
- [x] 로그인 시 유저 ID 전역 상태로 관리
- [x] 학습 홈 비회원 입장 BottomSheet 추가
- [x] 비회원 학습 탭 능력치 상위 퍼센트 "??"로 표기
