### ISSUE TITLE
feat: 용어 학습 레이아웃 추가

### ISSUE THREAD

**Issue by azure-553** [dnd-side-project/dnd-11th-10-frontend#13]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

<br />

용어학습을 위한 테스트 레이아웃을 구현합니다.

## ✅ To-do
- [x] 퀴즈 시작 레이아웃 스타일링
- [x] 퀴즈 타입 레이아웃 스타일링
- [x] 문제 Progress bar 추가
