### ISSUE TITLE
feat: 용어 목록 페이지 UI 작업

### ISSUE THREAD

**Issue by lsy20140** [dnd-side-project/dnd-11th-10-frontend#20]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

용어 목록 페이지 UI 작업

![image](https://github.com/user-attachments/assets/d063bf12-53b3-4fc6-9aeb-9319e96f7188)

<br />

## ✅ To-do
- [x] 검색 헤더- 공통 UI 컴포넌트로 생성
- [x] 카테고리 구현
- [x] 용어 개별 컴포넌트 UI 작업
- [x] 페이지 상단으로 이동하는 플로팅 버튼 구현
- [ ] 정렬 bottomSheet (bottomSheet 공통 컴포넌트로 분리)
