### ISSUE TITLE
feat: 용어 퀴즈 시작 및 문제 구현하기

### ISSUE THREAD

**Issue by azure-553** [dnd-side-project/dnd-11th-10-frontend#21]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

<br />
퀴즈 부분 및 결과 부분의 레이아웃을 작업합니다.

## ✅ To-do
- [x] 퀴즈 시작 부분 레이아웃 작업
- [x] 퀴즈 목업 데이터 가져오기
- [x] 퀴즈 문제 부분 레이아웃 작업
- [x] 퀴즈 진행 기능 구현
