### ISSUE TITLE
feat: 용어 상세 페이지 UI 작업

### ISSUE THREAD

**Issue by lsy20140** [dnd-side-project/dnd-11th-10-frontend#27]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

![image](https://github.com/user-attachments/assets/0fad5764-ffb4-4d40-ad37-1455019381f1)

<br />

## ✅ To-do
- [x] 용어 상세, 예문, 문의 버튼 UI 작업
- [x] 댓글 목록 컴포넌트 UI 작업(댓글 없는 경우 UI 추가)
- [x] 공통 Textarea 컴포넌트 구현 및 스토리 작성
- [x] 댓글 등록 Textarea 추가
