### ISSUE TITLE
design: 홈(메인) 페이지 WordItem 컴포넌트 UI 수정, custom Typography 적용 안 되는 부분 수정

### ISSUE THREAD

**Issue by lsy20140** [dnd-side-project/dnd-11th-10-frontend#31]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

1. WordItem width 수정
  변경 전) 하나의 WordItem이 가로 화면 전체 fill 되는 형태
  **변경 후) 단어 길이에 맞게 너비 조정**

2. 북마크 아이콘/기능 제거

3. 카테고리 태그 위치 변경

4. custom Typography 설정 후 적용 안 되는 부분 수정

<br />

## ✅ To-do
- [ ] WordItem width 단어 길이에 맞게 변경
- [ ] 북마크 제거
- [ ] 카테고리 태그 위치 변경
- [ ] custom Typography 설정 후 적용 안 되는 부분 수정
