### ISSUE TITLE
design: 피드백 이후 디자인 수정 사항 반영

### ISSUE THREAD

**Issue by lsy20140** [dnd-side-project/dnd-11th-10-frontend#37]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

- 피드백 이후 수정된 부분 전반적으로 반영하기

<br />

## ✅ To-do

피드백

- [x] color 변경된 부분 전체 수정
- [x] line-height 변경 사항 style/theme/fontSize.ts 반영
- [x] ux writing 변경 사항 전체 반영
- [x] checkbox 색상 변경
- [ ] 메인 댓글 목록 item- 비회원인 경우 메뉴 아이콘 hide
