### ISSUE TITLE
feat: 메인(홈) 페이지 Header 컴포넌트, Tab 구현 및 레이아웃 구성

### ISSUE THREAD

**Issue by lsy20140** [dnd-side-project/dnd-11th-10-frontend#4]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

로그인 여부에 따른 Header 구현

다음과 같은 폴더 구조 적용
app/home/layout.tsx(탭 구현)
app/home/learning
app/home/dictionary

### 로그인O

![image](https://github.com/user-attachments/assets/d600a59d-2c92-4df9-8b70-c786e884f7ee)
<br/>

### 로그인X

![image](https://github.com/user-attachments/assets/91a3ff6e-8c01-4706-86b9-ab4fe5a81a98)

<br />

## ✅ To-do
- [ ] Header 컴포넌트 구현(로그인 여부 고려)
- [ ] Tab 컴포넌트 구현 및 선택된 탭에 따른 페이지 보여주기
- [ ] 검색 아이콘, 프로필 또는 로그인 버튼 클릭 시 해당 페이지로 라우팅
