### ISSUE TITLE
feat: 별별 저장소 페이지 UI 작업

### ISSUE THREAD

**Issue by lsy20140** [dnd-side-project/dnd-11th-10-frontend#42]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

별별 저장소 페이지 전체 UI 작업, 컴포넌트 분리 및 수정
![image](https://github.com/user-attachments/assets/466ae7f9-b810-4f3b-96a6-45e0cd56c292)

<br />

## ✅ To-do
- [x] 사전 용어 목록 WordItem 컴포넌트 수정(북마크 아이콘 show/hide)
- [x] 북마크 버튼 컴포넌트 구현
- [x] TabFilter shared 컴포넌트로 분리 및 수정
- [x] Header 컴포넌트 분리 및 구현
- [x] 페이지 전체  UI 작업
