### ISSUE TITLE
feat: 사전 탭 페이지 UI 작업

### ISSUE THREAD

**Issue by lsy20140** [dnd-side-project/dnd-11th-10-frontend#5]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

- 피그마 작업물을 기반으로 사전 탭 페이지 UI 작업 진행
- 각 카드 컴포넌트 내 텍스트의 최대 표기 글자수 고려
<br />

![image](https://github.com/user-attachments/assets/77dd208f-91bb-4d07-b19a-8815fa25a79b)

## ✅ To-do
- [x] 용어 리스트 개별 컴포넌트 UI 작업(학습, 사전 탭 공통)
- [x] 용어 카테고리 태그 공통 컴포넌트 생성
- [ ] 지금 반응이 뜨거운 댓글 목록 및 개별 컴포넌트 UI 작업
- [x] #14
- [ ] #15
