### ISSUE TITLE
feat: 용어 사전 목록 조회 API 연동

### ISSUE THREAD

**Issue by lsy20140** [dnd-side-project/dnd-11th-10-frontend#50]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

 axios instance 세팅 후 용어 사전 목록 조회 API 연동 진행

<br />

## ✅ To-do
- [ ] axios instance 세팅
- [ ] 용어 사전 목록 조회 API 연동
- [ ] 무한스크롤 구현(no-offset)
