### ISSUE TITLE
feat:  (관리자) 용어 등록 페이지 구현

### ISSUE THREAD

**Issue by lsy20140** [dnd-side-project/dnd-11th-10-frontend#51]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

- 용어 등록 페이지 간단한 UI 작업
- 용어 등록 api 연동

<br />

## ✅ To-do
- [x] 홈 화면 구성(용어 등록, 용어 목록 조회, 신고 목록 조회)
- [x] 용어 등록 페이지 UI 작업
- [ ] 용어 등록 api 연동
