### ISSUE TITLE
design: 디자인 변경 사항 적용

### ISSUE THREAD

**Issue by lsy20140** [dnd-side-project/dnd-11th-10-frontend#64]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

- 홈, EmptyLayout 에 피그마 기준 새로 제작된 일러 및 아이콘 모두 적용합니다.
- hover 시 background color 변하는 경우 적용합니다.
- '실무 용어' 텍스트 -> '용어'로 모두 변경합니다.

<br />

## ✅ To-do
- [x] 일러 및 아이콘 적용
- [x] hover 시 bg 변하는 컴포넌트 적용
- [x] '실무 용어' -> '용어' 텍스트 변경
