### ISSUE TITLE
feat: 학습 탭 페이지 UI 작업

### ISSUE THREAD

**Issue by lsy20140** [dnd-side-project/dnd-11th-10-frontend#7]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

학습 탭 페이지 UI 작업(기능 X)

이미지 참고
![학습 홈 비회원 (1)](https://github.com/user-attachments/assets/8b5e24f8-b1f7-4fc7-ad51-70f52f7008b1)

<br />

## ✅ To-do
- [ ] 각 컴포넌트의 해당 페이지로 라우팅 설정
- [ ] 오늘 날짜 표기
- [ ] chart 형태에 사용가능한 svg 파일 생성
