### ISSUE TITLE
feat: Snackbar 컴포넌트 구현 및 스토리 작성

### ISSUE THREAD

**Issue by lsy20140** [dnd-side-project/dnd-11th-10-frontend#72]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

- Snackbar 컴포넌트 구현

<br />

## ✅ To-do
- [ ] Snackbar에 필요한 데이터 상수화
- [ ] Snackbar 컴포넌트 UI 작업
- [ ] 상태 관리 및 custom hook 구현
- [ ] 스토리 작성
