### ISSUE TITLE
design: 퀴즈 부분 변경된 디자인 & 공통 컴포넌트 적용

### ISSUE THREAD

**Issue by azure-553** [dnd-side-project/dnd-11th-10-frontend#80]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

<br />

- 임시로 작성한 코드를 제거하고, 공통으로 작성된 컴포넌트로 변경합니다
- 변경된 디자인을 적용합니다

## ✅ To-do
- [x] 이전 & 다음 버튼 변경
- [x] 텍스트 하이라이트 추가
- [x] 레이아웃 변경사항 적용
