### ISSUE TITLE
feat: 프로필 API 연결 로직 작성

### ISSUE THREAD

**Issue by azure-553** [dnd-side-project/dnd-11th-10-frontend#84]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

<br />

- 프로필 API를 연결하는 로직을 작성하고, 기능을 구현합니다

## ✅ To-do
- [x] 프로필 API 연결
- [x] 데이터가 올바르게 넘어갔는지 테스트
- [x] refresh-token 사용로직 추가
