### ISSUE TITLE
feat: 검색 페이지 레이아웃 추가

### ISSUE THREAD

**Issue by azure-553** [dnd-side-project/dnd-11th-10-frontend#90]
## 🖥 작업 설명
> 작업하고자 하는 내용에 대해 간단히 설명해주세요.

<br />

- 검색 페이지의 레이아웃을 추가합니다

## ✅ To-do
- [ ] Input 컴포넌트 추가
- [ ] 용어 순위 컴포넌트 추가
- [ ] 용어 순위 컴포넌트 스토리북 작성
- [ ] 업데이트 util함수 추가
